const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'..','PreSonus_IOStation.js'),'utf8').replace(/\r\n/g,'\n');
const s={};vm.createContext(s);
const bypassLEDStart=source.indexOf('function updateBypassLED(context)');
const bypassLEDend=source.indexOf('// BYPASS toggles the mode effect;',bypassLEDStart);
assert(bypassLEDStart>=0&&bypassLEDend>bypassLEDStart);
vm.runInContext(source.slice(bypassLEDStart,bypassLEDend),s);
const effectStart=source.indexOf('function toggleModeEffect(context)');
const effectEnd=source.indexOf('function updateKnobModeLEDs(',effectStart);
assert(effectStart>=0&&effectEnd>effectStart);
vm.runInContext(source.slice(effectStart,effectEnd),s);
const routingStart=source.indexOf('function assignButtonRouting(mapping)');
const routingEnd=source.indexOf('for (var buttonIndex =',routingStart);
assert(routingStart>=0&&routingEnd>routingStart);
vm.runInContext(source.slice(routingStart,routingEnd),s);
s.state={knobMode:'HighPass',shiftEnabled:'0',highPassEnabled:'0',knobPressRouted:''};
s.ctx={getState:k=>s.state[k]||'',setState:(k,v)=>s.state[k]=v};
s.cBypass=3;s.buttons={};s.surface={makeCustomValueVariable:()=>({setProcessValue:()=>{}})};
s.selectedTrackToggleValues={};s.isTrackFaderBypassMode=()=>false;s.isMouseLinkMode=()=>false;
s.isMetronomeBypassMode=()=>false;s.resolveKnobModeButton=(_,name)=>name;
let enabled=0,polarity=0,bypassLED=false;const hpWrites=[],phaseWrites=[];
s.highPassEnabledFeedbackValue={getProcessValue:()=>enabled,setProcessValue:(_,v)=>{enabled=v;hpWrites.push(v)}};
s.polarityFeedbackValue={getProcessValue:()=>polarity,setProcessValue:(_,v)=>{polarity=v;phaseWrites.push(v)}};
s.setTransportLed=(_,note,on)=>{if(note===s.cBypass)bypassLED=on};
s.updateHighPassLED=()=>{};
const pushStart=source.indexOf('mSection.knob_Press.mSurfaceValue.mOnProcessValueChange = function(context, value) {');
const pushEnd=source.indexOf('// Korg zoom pattern:',pushStart);
assert(pushStart>=0&&pushEnd>pushStart);
s.mSection={knob_Press:{mSurfaceValue:{}}};
vm.runInContext(source.slice(pushStart,pushEnd),s);
const push=s.mSection.knob_Press.mSurfaceValue.mOnProcessValueChange;
for(const [initial,expected] of [[0,1],[1,0]]){
  enabled=initial;s.state.highPassEnabled=String(initial);hpWrites.length=0;
  push(s.ctx,1);push(s.ctx,1);push(s.ctx,0);
  assert.equal(enabled,expected);assert.equal(polarity,0);assert.deepEqual(hpWrites,[expected]);
}

const physical={mSurfaceValue:{}};
s.assignButtonRouting({normalName:'Bypass',shiftedName:'BypassAll',physicalButton:physical});
const bypass=physical.mSurfaceValue.mOnProcessValueChange;
s.state.knobMode='HighPass';s.state.shiftEnabled='0';enabled=0;polarity=0;phaseWrites.length=0;
bypass(s.ctx,1);bypass(s.ctx,1);bypass(s.ctx,0);
assert.equal(polarity,1);assert.equal(enabled,0);assert.deepEqual(phaseWrites,[1]);
s.updateBypassLED(s.ctx);assert.equal(bypassLED,true);

s.state.knobMode='PreGain';s.state.shiftEnabled='1';s.updateBypassLED(s.ctx);assert.equal(bypassLED,true);
bypass(s.ctx,1);bypass(s.ctx,0);
assert.equal(polarity,0);assert.deepEqual(phaseWrites,[1,0]);
s.updateBypassLED(s.ctx);assert.equal(bypassLED,false);
console.log('PASS: knob push alone toggles High Pass; BYPASS toggles phase in both Channel modes');
