const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const s={require:()=>require('../api/midiremote_api_v1')};vm.createContext(s);
vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..','PreSonus_IOStation.js'),'utf8'),s);
const state={},ctx={getState:k=>state[k]||'',setState:(k,v)=>state[k]=v};
const bindings=[];s.page.makeValueBinding=(input,host)=>{const b={input,host,setSubPage(p){this.page=p;return this},setValueTakeOverModeScaled(){return this}};bindings.push(b);return b};
s.setupMouseLockFeedback();s.assignKnobControls();
const lockBinding=bindings.find(b=>b.input===s.mouseLockFeedbackValue);assert.equal(lockBinding.host,s.page.mHostAccess.mMouseCursor.mValueLocked);assert.equal(lockBinding.page,undefined);
assert(bindings.some(b=>b.input===s.knob&&b.host===s.page.mHostAccess.mMouseCursor.mValueUnderMouse&&b.page===s.knobModes.Mouse));
let locked=0,writes=0,shiftLED=false,bypassLED=false;const colors=[];
s.mouseLockFeedbackValue.getProcessValue=()=>locked;s.mouseLockFeedbackValue.setProcessValue=(ctx,v)=>{locked=v;writes++;s.mouseLockFeedbackValue.mOnProcessValueChange(ctx)};
s.setTransportLed=(_,note,on)=>{if(note===s.cBypass)bypassLED=on};s.onLED=(_,note)=>{if(note===s.cShift)shiftLED=true};s.offLED=(_,note)=>{if(note===s.cShift)shiftLED=false};s.setRGBLED_color=(_,note,color)=>colors.push([note,Array.from(color)]);
s.faderModes.Track.mAction.mActivate.trigger=()=>{};s.updateTouchLED=()=>{};s.knob.getProcessValue=()=>.5;
s.buttons.Link.setProcessValue=(ctx,v)=>{if(v)s.activateKnobMode(ctx,'Link',{})};s.buttons.Mouse.setProcessValue=(ctx,v)=>{if(v)s.activateKnobMode(ctx,'Mouse',{})};s.buttons.Bypass.setProcessValue=()=>{};
s.activateKnobMode(ctx,'Link',{});const link=s.mSection.btn_Link.mSurfaceValue.mOnProcessValueChange;
link(ctx,1);link(ctx,1);link(ctx,0);assert.equal(state.knobMode,'Mouse');assert.equal(shiftLED,true);assert.equal(state.faderTarget,'Track');assert(colors.some(([n,c])=>n===s.cLink&&c.join(',')==='0,0,127'));
const push=s.mSection.knob_Press.mSurfaceValue.mOnProcessValueChange;push(ctx,1);push(ctx,1);push(ctx,0);assert.equal(locked,1);assert.equal(writes,1);assert.equal(bypassLED,true);
link(ctx,1);link(ctx,0);assert.equal(state.knobMode,'Link');assert.equal(shiftLED,false);assert.equal(locked,1);assert.equal(writes,1);
const shift=s.uSection.btn_Shift.mSurfaceValue.mOnProcessValueChange;shift(ctx,1);shift(ctx,0);assert.equal(state.knobMode,'Mouse');assert.equal(bypassLED,true);assert.equal(writes,1);
const bypass=s.uSection.btn_Bypass.mSurfaceValue.mOnProcessValueChange;bypass(ctx,1);bypass(ctx,1);bypass(ctx,0);assert.equal(locked,0);assert.equal(bypassLED,false);assert.equal(writes,2);
locked=1;s.mouseLockFeedbackValue.mOnProcessValueChange(ctx);assert.equal(bypassLED,true);
shift(ctx,1);shift(ctx,0);assert.equal(state.knobMode,'Link');assert.equal(locked,1);
console.log('PASS: mouse binding, persistent host lock, both lock buttons, LED feedback, Link/SHIFT transitions and track fader');
