const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const s={require:()=>require('../api/midiremote_api_v1')};vm.createContext(s);
vm.runInContext(fs.readFileSync(require('path').join(__dirname,'..','PreSonus_IOStation.js'),'utf8'),s);
const state={},ctx={getState:k=>state[k]||'',setState:(k,v)=>state[k]=v};
let gain=.5,polarity=0;const colors=[],writes=[];
s.preGainFeedbackValue.getProcessValue=()=>gain;
s.preGainFeedbackValue.setProcessValue=(_,v)=>{gain=v;writes.push(v)};
s.polarityFeedbackValue.getProcessValue=()=>polarity;
s.polarityFeedbackValue.setProcessValue=(_,v)=>polarity=v;
s.setRGBLED_color=(_,note,color)=>colors.push(Array.from(color));s.onLED=()=>{};
let bypass;s.setTransportLed=(_,note,on)=>{if(note===s.cBypass)bypass=on};
for(const [v,c] of [[0,[0,0,127]],[.25,[63.5,63.5,127]],[.5,[127,127,127]],[.75,[127,63.5,127]],[1,[127,0,127]]])assert.deepEqual(Array.from(s.getPreGainColor(v)),c);
state.knobMode='PreGain';s.preGainFeedbackValue.mOnProcessValueChange(ctx);assert.deepEqual(colors.pop(),[127,127,127]);
s.toggleModeEffect(ctx);s.updateBypassLED(ctx);assert.equal(polarity,1);assert.equal(bypass,true);
s.toggleModeEffect(ctx);s.updateBypassLED(ctx);assert.equal(polarity,0);assert.equal(bypass,false);
gain=.1;const push=s.mSection.knob_Press.mSurfaceValue.mOnProcessValueChange;push(ctx,1);push(ctx,1);push(ctx,0);assert.deepEqual(writes,[.5]);
s.faderModes.Track.mAction.mActivate.trigger=()=>{};s.updateKnobModeLEDs=()=>{};s.updateTouchLED=()=>{};s.knob.getProcessValue=()=>.5;
s.activateKnobMode(ctx,'PreGain',{});assert.equal(state.faderTarget,'Track');
state.shiftEnabled='1';s.buttons.Bypass.setProcessValue=()=>{};
const press=s.uSection.btn_Bypass.mSurfaceValue.mOnProcessValueChange;press(ctx,1);press(ctx,1);press(ctx,0);assert.equal(polarity,1);
state.knobMode='Pan';s.preGainFeedbackValue.mOnProcessValueChange(ctx);assert.equal(colors.length,0);
console.log('PASS: pre-gain gradient, host feedback, reset, polarity LED/toggle, shifted BYPASS and track fader');
